//  Generated by StarUML(tm) C++ Add-In
/*
Jerome Hayes Jr
5/5/14
instructor.cpp
Implementation of the instructor.h file. 
*/

#include <iostream>
#include <string>
#include <vector>

using namespace std;

#include "Instructor.h"

Instructor::Instructor() 
{
    salary = 0;
}

Instructor::Instructor(string n, string d, string g, int s) : Person(n,d,g)
{
    salary = s;
}

void Instructor::print() 
{
    if (gender == "M")
    {
        cout << "Mr. ";
    }
    else // assuming gender == "F"
    {
            cout << "Ms. ";
    }
    Person::print();
    cout << "    Instructor, Salary: " << salary << endl;
}

