//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Instructor.h
//  @ Date : 5/5/2014
//  @ Author : Jerome Hayes Jr
//
//

#include <iostream>
#include <string>
#include <vector>
#include "Person.h"

#if !defined(_INSTRUCTOR_H)
#define _INSTRUCTOR_H

using namespace std;


class Instructor: public Person {
public:
    Instructor();
    Instructor(string n, string d, string g, int s);
    virtual void print();
protected:
    int salary;
};

#endif  //_INSTRUCTOR_H
