//  Generated by StarUML(tm) C++ Add-In
/*
Jerome Hayes Jr
5/5/14
Person.cpp
Implementation of the Person.h
*/

#include <iostream>
#include <string>
#include <vector>

using namespace std;

#include "Person.h"

Person::Person() 
{
    name = "";
    dob = "";
    gender = "";
}

Person::Person(string n, string d, string g) 
{
    name = n;
    dob = d;
    gender = g;
}

void Person:: print() 
{
    cout << name << " " << dob << endl;
}

