//  Generated by StarUML(tm) C++ Add-In
/*
Jerome Hayes Jr
5/5/14
Person.h
Header file of the base Person class 
*/
#ifndef PERSON_H
#define PERSON_H
#include <iostream>
#include <string>
#include <vector>

using namespace std;


class Person {
public:
    Person();
    Person(string n, string d, string g);
    virtual void print();
protected:
    string name;
    string dob;
    string gender;
};

#endif  //_PERSON_H
