//  Generated by StarUML(tm) C++ Add-In
/*
Jerome Hayes Jr
5/5/14
Student.cpp
Implementation of the Student.h functions 
*/

#include <iostream>
#include <string>
#include <vector>

using namespace std;

#include "Student.h"

Student::Student() 
{
    Person::Person();
    major = "";
}

Student::Student(string n, string d, string g, string m) : Person(n, d, g)
{
    major = m;
}

void Student::print() 
{
    Person::print();
    cout << "    Student, Major: " << major << endl;
}

